[package]
name = "the_heck"
description = "A command line corrector inspired by thefuck"
authors = ["Elizabeth Oda"]
version = "0.1.5"
readme = "README.md"
repository = "https://github.com/elizabeth-oda/the-heck"
license = "MIT"
edition = "2021"

[dependencies]
console = "0.15.5"

[[bin]]
name = "heck"
path = "src/main.rs"

[target."cfg(unix)".dev-dependencies]
libc = "0.2"
tempfile = "3"
