// These are command words, never command lines containing flags or arguments.
const GIT: &[&str] = &[
    "add",
    "am",
    "annotate",
    "apply",
    "archive",
    "bisect",
    "blame",
    "branch",
    "bugreport",
    "bundle",
    "cat-file",
    "check-attr",
    "check-ignore",
    "check-mailmap",
    "check-ref-format",
    "checkout",
    "checkout-index",
    "cherry",
    "cherry-pick",
    "clean",
    "clone",
    "column",
    "commit",
    "commit-graph",
    "commit-tree",
    "config",
    "count-objects",
    "credential",
    "credential-cache",
    "credential-store",
    "daemon",
    "describe",
    "diagnose",
    "diff",
    "diff-files",
    "diff-index",
    "diff-tree",
    "difftool",
    "fast-export",
    "fast-import",
    "fetch",
    "fetch-pack",
    "filter-branch",
    "fmt-merge-msg",
    "for-each-ref",
    "for-each-repo",
    "format-patch",
    "fsck",
    "fsck-objects",
    "gc",
    "get-tar-commit-id",
    "grep",
    "hash-object",
    "help",
    "hook",
    "http-backend",
    "http-fetch",
    "http-push",
    "imap-send",
    "index-pack",
    "init",
    "init-db",
    "instaweb",
    "interpret-trailers",
    "log",
    "ls-files",
    "ls-remote",
    "ls-tree",
    "mailinfo",
    "mailsplit",
    "maintenance",
    "merge",
    "merge-base",
    "merge-file",
    "merge-index",
    "merge-tree",
    "mergetool",
    "mktag",
    "mktree",
    "multi-pack-index",
    "mv",
    "name-rev",
    "notes",
    "pack-objects",
    "pack-redundant",
    "pack-refs",
    "patch-id",
    "pickaxe",
    "prune",
    "prune-packed",
    "pull",
    "push",
    "quiltimport",
    "range-diff",
    "read-tree",
    "rebase",
    "receive-pack",
    "reflog",
    "remote",
    "repack",
    "replace",
    "request-pull",
    "rerere",
    "reset",
    "restore",
    "rev-list",
    "rev-parse",
    "revert",
    "rm",
    "send-pack",
    "shell",
    "shortlog",
    "show",
    "show-branch",
    "show-index",
    "show-ref",
    "sparse-checkout",
    "stage",
    "stash",
    "status",
    "stripspace",
    "submodule",
    "subtree",
    "switch",
    "symbolic-ref",
    "tag",
    "unpack-file",
    "unpack-objects",
    "update-index",
    "update-ref",
    "update-server-info",
    "upload-archive",
    "upload-pack",
    "var",
    "verify-commit",
    "verify-pack",
    "verify-tag",
    "version",
    "whatchanged",
    "worktree",
    "write-tree",
];
const CARGO: &[&str] = &[
    "add",
    "b",
    "bench",
    "build",
    "c",
    "check",
    "clean",
    "clippy",
    "config",
    "d",
    "doc",
    "fetch",
    "fix",
    "fmt",
    "generate-lockfile",
    "git-checkout",
    "help",
    "info",
    "init",
    "install",
    "locate-project",
    "login",
    "logout",
    "metadata",
    "miri",
    "new",
    "owner",
    "package",
    "pkgid",
    "publish",
    "r",
    "read-manifest",
    "remove",
    "report",
    "rm",
    "run",
    "rustc",
    "rustdoc",
    "search",
    "t",
    "test",
    "tree",
    "uninstall",
    "update",
    "vendor",
    "verify-project",
    "version",
    "yank",
];

pub(crate) const PROGRAMS: &[&str] = &["cargo", "gh", "git"];

// Git 2.43 help and gh 2.86.0 `gh help reference`.
// Stack: github/gh-stack README at d4ab7ab47e5b3e3708a27c8c42abcdf4bc321419.
// Each row contains command words, never options or argument values.
const GROUPS: &[(&str, &str)] = &[
    ("git remote", "add rename remove rm set-head set-branches get-url set-url show prune update"),
    ("git stash", "list show drop pop apply branch push save clear create store"),
    ("git worktree", "add list lock move prune remove repair unlock"),
    ("git submodule", "add status init deinit update set-branch set-url summary foreach sync absorbgitdirs"),
    ("git bisect", "start bad good new old terms skip next reset visualize view replay log run"),
    ("git sparse-checkout", "init list set add reapply disable check-rules"),
    ("gh", "agent-task alias api attestation auth browse cache codespace completion config copilot extension gist gpg-key help issue label org pr preview project release repo ruleset run search secret ssh-key stack status variable workflow"),
    ("gh agent-task", "create list view"),
    ("gh alias", "delete import list set"),
    ("gh attestation", "download trusted-root verify"),
    ("gh auth", "login logout refresh setup-git status switch token"),
    ("gh cache", "delete list"),
    ("gh codespace", "code cp create delete edit jupyter list logs ports rebuild ssh stop view"),
    ("gh codespace ports", "forward visibility"),
    ("gh config", "clear-cache get list set"),
    ("gh extension", "browse create exec install list remove search upgrade"),
    ("gh gist", "clone create delete edit list rename view"),
    ("gh gpg-key", "add delete list"),
    ("gh issue", "close comment create delete develop edit list lock pin reopen status transfer unlock unpin view"),
    ("gh label", "clone create delete edit list"),
    ("gh org", "list"),
    ("gh pr", "checkout checks close comment create diff edit list lock merge ready reopen revert review status unlock update-branch view"),
    ("gh preview", "prompter"),
    ("gh project", "close copy create delete edit field-create field-delete field-list item-add item-archive item-create item-delete item-edit item-list link list mark-template unlink view"),
    ("gh release", "create delete delete-asset download edit list upload verify verify-asset view"),
    ("gh repo", "archive autolink clone create delete deploy-key edit fork gitignore license list rename set-default sync unarchive view"),
    ("gh repo autolink", "create delete list view"),
    ("gh repo deploy-key", "add delete list"),
    ("gh repo gitignore", "list view"),
    ("gh repo license", "list view"),
    ("gh ruleset", "check list view"),
    ("gh run", "cancel delete download list rerun view watch"),
    ("gh search", "code commits issues prs repos"),
    ("gh secret", "delete list set"),
    ("gh ssh-key", "add delete list"),
    ("gh variable", "delete get list set"),
    ("gh workflow", "disable enable list run view"),
    ("gh stack", "init add checkout rebase modify sync push submit link merge view unstack up down top bottom trunk switch feedback alias"),
];

pub(crate) fn children(path: &str) -> Vec<&'static str> {
    match path {
        "git" => GIT.to_vec(),
        "cargo" => CARGO.to_vec(),
        _ => GROUPS
            .iter()
            .find(|(name, _)| *name == path)
            .map(|(_, words)| words.split_whitespace().collect())
            .unwrap_or_default(),
    }
}

/// Built-in aliases have known grammar; configured aliases remain opaque.
pub(crate) fn canonical<'a>(path: &str, word: &'a str) -> &'a str {
    match (path, word) {
        ("gh", "agent" | "agents" | "agent-tasks") => "agent-task",
        ("gh", "at") => "attestation",
        ("gh", "cs") => "codespace",
        ("gh", "ext" | "extensions") => "extension",
        ("gh", "rs") => "ruleset",
        ("gh pr", "co") => "checkout",
        ("gh secret" | "gh variable", "remove") => "delete",
        ("gh stack", "delete") => "unstack",
        (
            "gh gist" | "gh issue" | "gh pr" | "gh release" | "gh repo" | "gh repo autolink",
            "new",
        ) => "create",
        (
            "gh alias" | "gh cache" | "gh codespace" | "gh config" | "gh extension" | "gh gist"
            | "gh gpg-key" | "gh issue" | "gh label" | "gh org" | "gh pr" | "gh project"
            | "gh release" | "gh repo" | "gh repo autolink" | "gh repo deploy-key"
            | "gh repo gitignore" | "gh repo license" | "gh ruleset" | "gh run" | "gh secret"
            | "gh ssh-key" | "gh variable" | "gh workflow",
            "ls",
        ) => "list",
        _ => word,
    }
}
